### PR TITLE
Update lightncandy.php

### PR DESCRIPTION
**Pull request by kfreiman**
Ability to pass data to a partial, if the first argument is not an array. 
`#each` example:

```handlebars
{{#each group.products}}
    {{>product_item test="test_str"}} {{!-- whill throw Calling unknown method: Product::test() --}}
{{/each}}
```

partial `product_item`:
```handlebars
{{test}} {{!-- brocked --}}
{{this.id}}
```

I think, for this purpose, it should be
```handlebars
{{#each group.products}}
    {{>product_item product=. test="test_str"}}
{{/each}}
```

and
```handlebars
{{test}}
{{product.id}}
```

### CODE REVIEW

**Comment by zordius** [comment]
I will create a jsfiddle to verify handlebars behavior first, thank you!

**Comment by zordius** [comment]
verified handlebars.js behavior: http://jsfiddle.net/ngk42ocn/

**when there is only named arguments, they will be merged into context then pass into partial**

Thank you for your contribution!

**Comment by zordius** [comment]
Sorry, I just realized lightncandy already supports `when there is only named arguments, they will be merged into context then pass into partial` , and the issue is about how to deal with `merge` logic in PHP just like JavaScript. I will create more tests to identify the issue.

For your case, you `product` seems to be an object but not an array. So we may need to deal with 'merge an associated array into an object` .

**Comment by zordius** [comment]
Now lightncandy can handle object/property merge when deal with partial, please try `{{>product_item test="test_str"}}` again, thanks.

**Comment by kfreiman** [comment]
Thank you, i'll try

**Pull request merged**
